application: ultimateroute
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /stylesheets
  static_dir: stylesheets

- url: /image
  static_dir: image

# Twitter Bootstrap
- url: /bootstrap
  static_dir: bootstrap

# Handler for front page
- url: /
  script: front.app

# All other pages require login
- url: /.*
  script: ultimateroute.app
  login: required

libraries:
- name: jinja2
  version: latest